[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "40214fcbc84e71868429c5e7cc8b70548773efb8"}
