[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.18.4"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "7d4f7730739bebd9e1d7edae0bb8f46933eb786f"}
